export const tvs = [
    { id: 1, marca: "Samsung", pulgadas: 55, sistema_operativo: "Tizen", wifi: false },
    { id: 2, marca: "LG", pulgadas: 65, sistema_operativo: "webOS", wifi: false },
    { id: 3, marca: "Sony", pulgadas: 50, sistema_operativo: "Google TV", wifi: false },
    { id: 4, marca: "TCL", pulgadas: 43, sistema_operativo: "Android TV", wifi: false },
    { id: 5, marca: "Hisense", pulgadas: 32, sistema_operativo: "VIDAA", wifi: false },
    { id: 6, marca: "Philips", pulgadas: 58, sistema_operativo: "SAPHI", wifi: false },
    { id: 7, marca: "Xiaomi", pulgadas: 43, sistema_operativo: "Android TV", wifi: false },
    { id: 8, marca: "Samsung", pulgadas: 75, sistema_operativo: "Tizen", wifi: true },
    { id: 9, marca: "LG", pulgadas: 32, sistema_operativo: "webOS", wifi: true },
    { id: 10, marca: "Panasonic", pulgadas: 55, sistema_operativo: "My Home Screen", wifi: false },
    { id: 11, marca: "TCL", pulgadas: 65, sistema_operativo: "Roku TV", wifi: true },
    { id: 12, marca: "Sony", pulgadas: 85, sistema_operativo: "Google TV", wifi: true },
    { id: 13, marca: "Hisense", pulgadas: 50, sistema_operativo: "Google TV", wifi: true },
    { id: 14, marca: "Philips", pulgadas: 65, sistema_operativo: "Android TV", wifi: true },
    { id: 15, marca: "BGH", pulgadas: 43, sistema_operativo: "Android TV", wifi: false },
    { id: 16, marca: "Noblex", pulgadas: 32, sistema_operativo: "VIDAA", wifi: false },
    { id: 17, marca: "RCA", pulgadas: 40, sistema_operativo: "Android TV", wifi: false },
    { id: 18, marca: "Samsung", pulgadas: 43, sistema_operativo: "Tizen", wifi: true },
    { id: 19, marca: "LG", pulgadas: 55, sistema_operativo: "webOS", wifi: true },
    { id: 20, marca: "Xiaomi", pulgadas: 55, sistema_operativo: "Google TV", wifi: true },
    { id: 21, marca: "Sony", pulgadas: 65, sistema_operativo: "Google TV", wifi: true },
    { id: 22, marca: "TCL", pulgadas: 50, sistema_operativo: "Google TV", wifi: true },
    { id: 23, marca: "Hisense", pulgadas: 43, sistema_operativo: "VIDAA", wifi: true },
    { id: 24, marca: "Panasonic", pulgadas: 43, sistema_operativo: "Android TV", wifi: true },
    { id: 25, marca: "Hitachi", pulgadas: 32, sistema_operativo: "Android TV", wifi: false },
    { id: 26, marca: "Samsung", pulgadas: 50, sistema_operativo: "Tizen", wifi: true },
    { id: 27, marca: "LG", pulgadas: 77, sistema_operativo: "webOS", wifi: true },
    { id: 28, marca: "Philips", pulgadas: 50, sistema_operativo: "Google TV", wifi: true },
    { id: 29, marca: "TCL", pulgadas: 32, sistema_operativo: "Android TV", wifi: true },
    { id: 30, marca: "Sony", pulgadas: 55, sistema_operativo: "Google TV", wifi: true },
    { id: 31, marca: "Hisense", pulgadas: 75, sistema_operativo: "VIDAA", wifi: true },
    { id: 32, marca: "Noblex", pulgadas: 50, sistema_operativo: "Google TV", wifi: true },
    { id: 33, marca: "BGH", pulgadas: 55, sistema_operativo: "Android TV", wifi: true },
    { id: 34, marca: "RCA", pulgadas: 32, sistema_operativo: "Roku TV", wifi: true },
    { id: 35, marca: "Xiaomi", pulgadas: 65, sistema_operativo: "Google TV", wifi: true },
    { id: 36, marca: "Samsung", pulgadas: 65, sistema_operativo: "Tizen", wifi: true },
    { id: 37, marca: "LG", pulgadas: 43, sistema_operativo: "webOS", wifi: true },
    { id: 38, marca: "Sharp", pulgadas: 50, sistema_operativo: "Android TV", wifi: false },
    { id: 39, marca: "JVC", pulgadas: 32, sistema_operativo: "Linux OS", wifi: false },
    { id: 40, marca: "TCL", pulgadas: 75, sistema_operativo: "Google TV", wifi: true },
    { id: 41, marca: "Hisense", pulgadas: 65, sistema_operativo: "Google TV", wifi: true },
    { id: 42, marca: "Philips", pulgadas: 75, sistema_operativo: "Android TV", wifi: true },
    { id: 43, marca: "Sony", pulgadas: 75, sistema_operativo: "Google TV", wifi: true },
    { id: 44, marca: "Samsung", pulgadas: 85, sistema_operativo: "Tizen", wifi: true },
    { id: 45, marca: "LG", pulgadas: 83, sistema_operativo: "webOS", wifi: true },
    { id: 46, marca: "Noblex", pulgadas: 43, sistema_operativo: "Android TV", wifi: true },
    { id: 47, marca: "BGH", pulgadas: 65, sistema_operativo: "Google TV", wifi: true },
    { id: 48, marca: "Hitachi", pulgadas: 50, sistema_operativo: "Android TV", wifi: true },
    { id: 49, marca: "Xiaomi", pulgadas: 75, sistema_operativo: "Google TV", wifi: true },
    { id: 50, marca: "Hyundai", pulgadas: 40, sistema_operativo: "Android TV", wifi: false },
]